export const {
  VITE_API_URL,
  DEV,
  VITE_CACHE_TIME,
  VITE_SEND_DELAY,
  VITE_BOT_APP,
  VITE_SHARE_URL,
  VITE_TELEGRAM_GROUP_LINK,
  VITE_TWITTER_USERNAME,
  VITE_TIKTOK_USERNAME,
} = import.meta.env;
